say_hi_for_testers:
  stage: test
  script:
    - echo "Hello World!"

say_hi_for_builders:
  stage: build
  script:
    - echo "Hello World!"

say_hi_for_deploy:
  stage: deploy
  script:
    - echo "Hello World!"
