/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package course_1;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import org.junit.*;

public class AppTest {

    App mApp;

    @Before
    public void Setup()
    {
        mApp = new App( 0 );
    }

    @Test
    public void multiplicationOfZeroIntegereShouldReturnZero() {
        assertEquals(  "max of 5 and 10 is 10", 10, mApp.max(5, 10) );
        assertEquals(  "max of -3 and 0 is 0", 0, mApp.max(-3, 0) );
        assertEquals( "max of -3 and -5 is -3", -3, mApp.max(-3, -5) );
    }


}
