/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package course_1;

import java.util.Optional;

public class App {

    public Integer max(Integer a ,Integer b){
       if(a!=null && b!=null) return a>b ? a:b;
       throw new ArithmeticException("We can not compare null value");

    }

}
